version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: banco_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SUA_SENHA
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - agronomIA_network

volumes:
  mysql_data:

networks:
  agronomIA_network:
    driver: bridge

