version: '3.9'

services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver
    ports:
      - "127.0.0.1:8978:8978"
    environment:
      - CB_SERVER_NAME=CloudBeaver Community
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    networks:
      - agronomIA_network
    restart: always

volumes:
  cloudbeaver_data:

networks:
  agronomIA_network:
    driver: bridge